#!/usr/bin/env sh
while : ; do
    echo "Watching for changes..."
    inotifywait -r -qq -e close_write -e create -e delete --exclude ^.+?\.sw.?$ .
    echo "File changed! Rebuilding documentation..."
    groc --only-render-newer
done
