#!/usr/bin/env python

import dapple
import yaml
import sys

configpath = "~/.dapple"

buildpath = "build.yaml"
with open(buildpath) as buildfile:
    if len(sys.argv) < 2:
        print "bad usage"
    else:
        if sys.argv[1] == "test":
            buildobj = yaml.load(buildfile)
            dapp = dapple.Dapp(buildobj)
            dapp.build()
            test_regex = ""
            if len(sys.argv) >= 3:
                test_regex = sys.argv[2]
            dapp.test(test_regex)
            dapp.write_binaries("/tmp/pack.json")
        if sys.argv[1] == "build":
            print "UNIMPLEMENTED - use `test`"
