#!/usr/bin/env python
#TODO  use this:  https://docs.python.org/2/library/argparse.html#module-argparse


import dapple
import yaml
import sys

import subprocess

configpath = "~/.dapple"
buildpath = "build.yaml"
with open(buildpath) as buildfile:
    if len(sys.argv) < 2:
        print "bad usage"
    else:
        cmd = sys.argv[1]
        dapp = None
        if cmd == "test" or cmd == "build" or cmd == "stage":
            buildobj = yaml.load(buildfile)
            dapp = dapple.Dapp(buildobj)

        if cmd == "test":
            dapp.build()
            test_regex = ""
            if len(sys.argv) >= 3:
                test_regex = sys.argv[2]
            dapp.test(test_regex)
        elif cmd == "stage":
            dapp.build()
            staging_dir = "/tmp/stage"
            if len(sys.argv) >= 3:
                staging_dir = sys.argv[2]
            dapp.write_binaries(staging_dir)
        elif cmd == "testnet": #TODO
            subprocess.call("geth --datadir devdatadir --networkid 42 --unlock 0 --password devdatadir/pass.txt --mine console", shell=True)
        else:
            print "Unrecognized option: " + sys.argv[1]


