#!/bin/sh -eu
# Make sure we have the same UID and GID as the host user
uid=`stat -c %u .` gid=`stat -c %g .`
groupmod -o -g $gid $GROUP || groupadd -o -g $gid $GROUP
useradd -o -u $uid -g $gid -d $HOME $USER
exec gosu $USER ${entrypoint-dapple} "$@"
