#!/bin/sh
exec docker run --rm -it --net=host --name=dapple-$$ \
-e HOME -e USER=`id -un` -e GROUP=`id -gn` \
-e entrypoint -w "`pwd`" -v "`pwd`:`pwd`" \
-v "$HOME/.npm:$HOME/.npm" \
-v "$HOME/.emacs:$HOME/.emacs:ro" \
-v "$HOME/.vimrc:$HOME/.vimrc:ro" \
-v "$HOME/.dapple:$HOME/.dapple" \
dbrock/dapple "$@"
